name: Main

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: dotnet build ./src/Avalonia.HtmlRenderer/Avalonia.HtmlRenderer.csproj -c Release
      - name: Pack
        run: dotnet pack ./src/Avalonia.HtmlRenderer/Avalonia.HtmlRenderer.csproj --no-build -o ./artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./artifacts/*.*
          retention-days: 5
          name: packages
